import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr


def send_study_email(
    recipient_email,
    subject,
    study_content,
    sender_email,
    sender_password,
    sender_name="Snap & Study"
):

    message = MIMEMultipart("alternative")

    message["From"] = formataddr(
        (sender_name, sender_email)
    )

    message["To"] = recipient_email
    message["Subject"] = subject

    # Plain text email
    plain_text = study_content

    # HTML email
    html_content = study_content.replace(
        "\n",
        "<br>"
    )

    html_body = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">

        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.7;
                color: #222;
                max-width: 800px;
                margin: auto;
                padding: 20px;
            }}

            h1 {{
                color: #2563eb;
            }}

            hr {{
                border: none;
                border-top: 1px solid #ddd;
                margin: 20px 0;
            }}

            .footer {{
                color: #777;
                font-size: 13px;
            }}
        </style>

    </head>

    <body>

        <h1>📚 Snap & Study</h1>

        <p>
            <strong>Complete Study Explanation</strong>
        </p>

        <hr>

        <div>
            {html_content}
        </div>

        <hr>

        <p class="footer">
            🤖 Generated by Snap & Study AI Study Assistant
        </p>

    </body>
    </html>
    """

    message.attach(
        MIMEText(
            plain_text,
            "plain",
            "utf-8"
        )
    )

    message.attach(
        MIMEText(
            html_body,
            "html",
            "utf-8"
        )
    )

    try:

        with smtplib.SMTP(
            "smtp.gmail.com",
            587
        ) as server:

            server.starttls()

            server.login(
                sender_email,
                sender_password
            )

            server.sendmail(
                sender_email,
                recipient_email,
                message.as_string()
            )

        return True, "Email sent successfully!"

    except smtplib.SMTPAuthenticationError:

        return False, (
            "Gmail authentication failed. "
            "Please check your Gmail address and App Password."
        )

    except smtplib.SMTPException as error:

        return False, (
            f"Email sending failed: {error}"
        )

    except Exception as error:

        return False, (
            f"Unexpected error: {error}"
        )